# Generated by Django 3.0.8 on 2020-07-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('url', models.CharField(max_length=200)),
                ('redirect_url', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('add_tm', models.DateTimeField(auto_now_add=True)),
                ('visits', models.IntegerField(default=0)),
            ],
        ),
    ]
