# Generated by Django 3.0.8 on 2020-10-31 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('url', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('redirect_url', models.CharField(max_length=200)),
                ('add_tm', models.DateTimeField(auto_now_add=True, verbose_name='add time')),
                ('total_clicks', models.IntegerField(default=0)),
            ],
        ),
    ]
