# Generated by Django 3.0.8 on 2020-07-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='redirect_url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
