# Generated by Django 3.0.8 on 2020-07-09 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200708_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='visits',
            new_name='total_clicks',
        ),
    ]
